server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    discovery:
      enabled: true
  security:
    user:
      name: disabled
      password: disabled

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: MyVerySecretSigningKey      # substitua por uma chave segura
  token:
    validity: 3600000                 # 1 hora em milissegundos
