server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    discovery:
      enabled: true
  security:
    user:
      name: disabled
      password: disabled

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

jwt:
  secret: dk1v9mOPWQZx4pl2ns7D5YRFv8sHg3tLbcxyqzABP0Lmns2Xkc   
  token:
    validity: 3600000
